# A simple tester of Board

In [1]:
import numpy as np

from brumaire.board import BoardData
from brumaire.constants import Suit, Role, CardStatus

In [2]:
BOARD_NUM = 3

In [3]:
board = BoardData.generate(BOARD_NUM)
board.cards[0]

array([[1, 3, 0, 0],
       [1, 3, 1, 0],
       [1, 4, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 2, 0],
       [1, 2, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 1, 0],
       [1, 3, 2, 0],
       [1, 0, 1, 0],
       [1, 3, 3, 0],
       [1, 1, 3, 0],
       [1, 2, 2, 0],
       [1, 0, 2, 0],
       [1, 0, 3, 0],
       [1, 4, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 4, 0],
       [1, 3, 4, 0],
       [1, 0, 5, 0],
       [1, 4, 2, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 0],
       [1, 2, 4, 0],
       [1, 1, 4, 0],
       [1, 1, 5, 0],
       [1, 0, 6, 0],
       [1, 4, 3, 0],
       [1, 3, 5, 0],
       [1, 2, 5, 0],
       [1, 3, 6, 0],
       [1, 1, 6, 0],
       [0, 0, 0, 0],
       [1, 1, 7, 0],
       [1, 3, 7, 0],
       [1, 2, 6, 0],
       [1, 3, 8, 0],
       [1, 1, 8, 0],
       [1, 0, 7, 0],
       [1, 2, 7, 0],
       [1, 0, 8, 0],
       [1, 4, 4, 0],
       [1, 4, 5, 0],
       [1, 4, 6, 0],
       [1, 1, 9, 0],
       [1, 4,

In [4]:
board.roles = np.repeat(
    np.array([[Role.NAPOLEON, Role.ALLY, Role.ALLY, Role.ALLY, Role.ADJUTANT]]),
    BOARD_NUM,
    axis=0,
)
board.cards[:, Suit.SPADE * 13 + 12, 3] = 1

In [5]:
copied_board = BoardData.from_vector(board.to_vector())
is_same = (
    np.all(copied_board.cards == board.cards)
    and np.all(copied_board.taken == board.taken)
    and np.all(copied_board.roles == board.roles)
    and np.all(copied_board.decl == board.decl)
    and np.all(copied_board.lead == board.lead)
)

assert is_same

In [6]:
board.cards[1, Suit.SPADE * 13 + 12, 0] = CardStatus.PLAYED
board.is_adj_revealed()

array([False,  True, False])

In [7]:
board.get_suits_map(np.array([Suit.HEART, Suit.JOKER]))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [8]:
board.decl[:, 0] = Suit.HEART
board.lead[:, 1] = Suit.DIAMOND

board.get_hand_filter(0)

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True,  True, False,
        False,  True, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False,  True,
    

In [9]:
board.get_filtered_hand_index(0)

array([[0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0]])

In [10]:
board.get_hand_filter(1)

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False,  True,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,
    

In [11]:
(board.get_hand(0, 1), board.get_hand(2, 2))

(array([False, False, False, False,  True,  True,  True, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,
         True, False, False, False, False, False,  True, False,  True,
        False, False, False,  True, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False]),
 array([False, False, False, False, False,  True, False,  True, False,
        False, False,  True, False, False, False, False,  True, False,
        False, False, False,  True, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False,
         True, False,  True, False, False,  True, False, False, False,
        False,  True, False, False, False, False, False, False, False]))

In [12]:
board = board.change_perspective_to_one(1)
board.cards[0]

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 2, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 3, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 4, 0],
       [1, 0, 5, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 6, 0],
       [0, 0, 0, 0],
       [1, 0, 7, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 8, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 9, 0],
       [0, 0,

In [13]:
board.get_strongest_for_each_suits()

array([[ 6, 13, 35, 46],
       [ 8, 24, 38, 45],
       [ 6, 24, 32, 45]])

In [14]:
board.roles

array([[3, 0, 0, 0, 1],
       [3, 3, 3, 2, 1],
       [3, 0, 0, 0, 1]])