In [1]:
import numpy as np

from brumaire.board import BoardData, generate_board
import brumaire

In [2]:
BOARD_NUM = 3

In [3]:
board = generate_board(BOARD_NUM)
board.cards[0]

array([[1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 3., 0., 0.],
       [1., 0., 2., 0.],
       [1., 3., 1., 0.],
       [1., 3., 2., 0.],
       [1., 4., 0., 0.],
       [1., 4., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 3., 3., 0.],
       [1., 0., 3., 0.],
       [1., 2., 0., 0.],
       [1., 4., 2., 0.],
       [1., 1., 1., 0.],
       [1., 2., 1., 0.],
       [1., 0., 4., 0.],
       [1., 1., 2., 0.],
       [1., 4., 3., 0.],
       [0., 0., 0., 0.],
       [1., 1., 3., 0.],
       [1., 2., 2., 0.],
       [1., 0., 5., 0.],
       [1., 3., 4., 0.],
       [1., 3., 5., 0.],
       [1., 2., 3., 0.],
       [1., 4., 4., 0.],
       [1., 2., 4., 0.],
       [1., 1., 4., 0.],
       [1., 4., 5., 0.],
       [1., 1., 5., 0.],
       [1., 4., 6., 0.],
       [1., 1., 6., 0.],
       [1., 0., 6., 0.],
       [1., 1., 7., 0.],
       [1., 3., 6., 0.],
       [1., 4., 7., 0.],
       [1., 2., 5., 0.],
       [1., 3., 7., 0.],
       [1., 2., 6., 0.],


In [4]:
board.roles = np.repeat(np.array([[
    brumaire.ROLE_NAPOLEON,
    brumaire.ROLE_ALLY,
    brumaire.ROLE_ALLY,
    brumaire.ROLE_ALLY,
    brumaire.ROLE_ADJUTANT
]]), BOARD_NUM, axis=0)
board.cards[:, brumaire.SUIT_SPADE * 13 + 12, 3] = 1

In [5]:
board = board.change_perspective(1)
board.cards[0]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 2., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 3., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 4., 0.],
       [0., 0., 0., 0.],
       [1., 0., 5., 0.],
       [0., 0., 0., 0.],
       [1., 0., 6., 0.],
       [0., 0., 0., 0.],
       [1., 0., 7., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [6]:
board.roles

array([[3, 0, 0, 0, 1],
       [3, 0, 0, 0, 1],
       [3, 0, 0, 0, 1]])